name: Daily Job Hunt

on:
  schedule:
    - cron: '0 23 * * *' # 日本時間の毎朝8時（UTC 23:00）に実行
  workflow_dispatch: # 手動でも実行できるようにするボタンを追加

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run Job Hunter App
      env:
        LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }} # LINEトークンを隠す設定
      run: python "job hunt app.py"